In [7]:
#from here: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
import torch

In [2]:
#construct a randomly-populated matrix by size (uses whatever values were in memory)
x = torch.empty(5,3)
x

tensor([[2.1781e-04, 1.0141e-11, 1.6779e+22],
        [6.4830e-10, 5.2428e-08, 4.0329e-08],
        [5.4422e+22, 8.1262e+20, 4.1470e-11],
        [4.2330e+21, 1.6534e+19, 3.0478e+32],
        [       nan,        nan, 4.8116e-24]])

In [3]:
#actually randomly initialized
x = torch.rand(5,3)
x

tensor([[0.0886, 0.2725, 0.4142],
        [0.8182, 0.8620, 0.3357],
        [0.3831, 0.2819, 0.1755],
        [0.6493, 0.9695, 0.8114],
        [0.6392, 0.7621, 0.9651]])

In [5]:
#a matrix of zeros with dtype long
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
#construct a tensor directly
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [8]:
#create one based on the existing one. will reuse the shape and dtype unless you overwrite
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
y = torch.randn_like(x, dtype=torch.float) #one like x but with different dtype
y

tensor([[ 0.3787, -0.6924,  0.1510],
        [-0.5839,  0.8193,  0.5209],
        [-1.0391,  1.8359,  0.2568],
        [ 1.3535, -1.0314, -0.1912],
        [ 1.2596, -1.0709,  2.1994]])

In [11]:
y.size()

torch.Size([5, 3])

In [13]:
x = torch.rand(5,3)

In [14]:
x + y #simple addition

tensor([[ 1.3423, -0.2985,  0.1834],
        [ 0.3530,  1.0182,  0.8592],
        [-0.7035,  2.4546,  0.3681],
        [ 1.6283, -0.8461,  0.6444],
        [ 1.7051, -0.5583,  2.9508]])

In [15]:
#or provide an output tensor for the result
result = torch.empty(5,3)
torch.add(x,y, out=result)
result

tensor([[ 1.3423, -0.2985,  0.1834],
        [ 0.3530,  1.0182,  0.8592],
        [-0.7035,  2.4546,  0.3681],
        [ 1.6283, -0.8461,  0.6444],
        [ 1.7051, -0.5583,  2.9508]])

In [16]:
#or add in place, always postfixed with underscore_
y.add_(x)
y

tensor([[ 1.3423, -0.2985,  0.1834],
        [ 0.3530,  1.0182,  0.8592],
        [-0.7035,  2.4546,  0.3681],
        [ 1.6283, -0.8461,  0.6444],
        [ 1.7051, -0.5583,  2.9508]])

In [17]:
#can use standard numpy indexing
x[:,1]

tensor([0.3939, 0.1989, 0.6187, 0.1853, 0.5126])

In [19]:
#can reshape using torch.view
x = torch.randn(4,4)
x

tensor([[ 0.8036,  0.4856, -0.1033,  1.6308],
        [-0.3364, -0.5002,  0.2619, -1.0575],
        [ 0.3701,  1.1160,  0.1906,  0.3251],
        [-0.2666, -0.9169,  0.5421,  0.0860]])

In [20]:
y = x.view(16)
y

tensor([ 0.8036,  0.4856, -0.1033,  1.6308, -0.3364, -0.5002,  0.2619, -1.0575,
         0.3701,  1.1160,  0.1906,  0.3251, -0.2666, -0.9169,  0.5421,  0.0860])

In [21]:
z = x.view(-1,8)
z

tensor([[ 0.8036,  0.4856, -0.1033,  1.6308, -0.3364, -0.5002,  0.2619, -1.0575],
        [ 0.3701,  1.1160,  0.1906,  0.3251, -0.2666, -0.9169,  0.5421,  0.0860]])

In [22]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
#use .item() to get the value of a one-element tensor
x = torch.randn(1)
x

tensor([0.1447])

In [24]:
x.item()

0.14469315111637115

In [25]:
import numpy

In [26]:
#converting back and forth is easy; and they share underlying memory locations (on CPU)
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [27]:
b = a.numpy() #this is not a separate object! it's just a pointer, apparently!
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [28]:
a.add_(1) #this also updates b!
a

tensor([2., 2., 2., 2., 2.])

In [29]:
b

array([2., 2., 2., 2., 2.], dtype=float32)